### ISSUE TITLE
Releasesにコンパイル済みのバイナリがないので、復活させてほしい。

### ISSUE THREAD

**Issue by TakaraShinya** [calloc134/openapi2runn#2]
# 概要
下記のリンク先にコンパイル済みバイナリファイルがあるとREADMEに記載されてるが、ファイルがないようです。

https://github.com/calloc134/openapi2runn/releases

**Comment by calloc134** [comment]
ビルドを行ったものをリリースとして公開しました。
ただし、当プログラムは現在メンテナンスされておらず、最新版のrunnで動作することが確認されておりません。
ご了承ください。

https://github.com/calloc134/openapi2runn/releases
